services:
  wordpressdb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - wordpressdb_data:/var/lib/mysql
  wordpress:
    depends_on:
      - wordpressdb
    image: wordpress
    ports:
      - 80
    environment:
      WORDPRESS_DB_HOST: wordpressdb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
  nginx:
    depends_on:
      - wordpress
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # 호스트의 파일과 컨테이너 내부의 파일과 매핑
    restart: always
    ports:
      - "80:80"
volumes:
  wordpressdb_data: {}
