services:
  mysql:
    image: mysql
    ports:
      - 4406:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=springbootdb
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=0000
    volumes:
      - /Users/joyoungsang/temp/mysql_data:/var/lib/mysql

  springboot:
    depends_on:
      - mysql
    image: board:0.0.1-SNAPSHOT
    ports:
      - 9090:8080

  react:
    depends_on:
      - springboot
    image: board-app:v3
    ports:
      - 90:80